### ISSUE TITLE
Why pullRequest/push event handlers has been removed?

### ISSUE THREAD

**Issue by denis-tingaikin** [ridedott/merge-me-action#849]
## Description

Currently master version of `merge-me-action` can not handle push, pull_request events. 

Example:
```
Warning: Unknown event pull_request, skipping.
```

It has been disabled here: https://github.com/ridedott/merge-me-action/commit/aa86df2c5166c6d5db956d54d7cf0176cdce73ff

**Question:** Could you clarify why it is not supported more?

**Comment by JrSchild** [comment]
Hi @denis-tingaikin

See [this GitHub anouncement](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/):
> Starting March 1st, 2021 workflow runs that are triggered by Dependabot from push, pull_request, pull_request_review, or pull_request_review_comment events will be treated as if they were opened from a repository fork. This means they will receive a read-only GITHUB_TOKEN and will not have access to any secrets available in the repository. This will cause any workflows that attempt to write to the repository to fail.

So this unfortunately breaks the merge me action because we no longer have access to a write token. The new recommendation is to use a separate workflow_run action as outlined in the README. I hope that clarifies it.

**Comment by denis-tingaikin** [comment]
@JrSchild Sounds good. Thanks! Will try and if workflow_run will help then I close the issue :)

**Comment by JrSchild** [comment]
@denis-tingaikin we discussed this internally as well and realized that the action could also be used outside the context of dependabot in which case you might still want to use the push or pull_request events so we plan to add them back hopefully later next week.
